### ISSUE TITLE
openssl s_client sometimes hangs, would be nice to have some timeout

### ISSUE THREAD

**Issue by agroszer** [brianreumere/gandi-automatic-dns#31]
Caught `openssl s_client` eating the CPU for days... would be nice to have some timeout

**Comment by br41-net** [comment]
I looked into this briefly and it doesn't seem like there's any easy, portable way to do it (most guidance suggests the `timeout` command from coreutils, which isn't available or installed by default on a lot of OSes). Something like [this StackOverflow answer](https://stackoverflow.com/a/11056286) looks like it might be portable enough, but is a lot more complex.

I'm going to hold off on adding anything right now (I don't really have the time to dedicate to figuring out a proper, portable solution), but I'll leave this issue open.

**Comment by Alexandero89** [comment]
Can confirm. Was hanging for some days.
Fixed it by prepending the timeout command in the crontab.

`timeout --signal=9 60 /path/to/scirpt [options] `

**Comment by brianreumere** [comment]
I added a note in the [installation section of the README](https://github.com/brianreumere/gandi-automatic-dns#installation) about using the `timeout` command. Thanks for reporting!
