### ISSUE TITLE
timeout on openssl calls

### ISSUE THREAD

**Issue by cyayon** [brianreumere/gandi-automatic-dns#38]
In some case, when Gandi API fail, I encountered some issue with infinite openssl calls.

I suggest you to add `timeout <seconds>` before each openssl calls.

For example (with a timeout of 15s) : 

```
129c117
<     printf "%s" "$tmp_message" | timeout 15 openssl s_client -quiet -connect "$gandi" 2> /dev/null | tail -1
---
>     printf "%s" "$tmp_message" | openssl s_client -quiet -connect "$gandi" 2> /dev/null | tail -1
254c242
<     printf "%s" "$tmp_message" | timeout 15 openssl s_client -quiet -connect "$gandi" 2> /dev/null
---
>     printf "%s" "$tmp_message" | openssl s_client -quiet -connect "$gandi" 2> /dev/null
```
 
thanks.

**Comment by brianreumere** [comment]
This was suggested in #31 too. Not all operating systems have the `timeout` command, so I won't add it to the script. It is mentioned in the [Installation section of the README](https://github.com/brianreumere/gandi-automatic-dns#installation) that you can run `timeout 15 gad...` though.
