### ISSUE TITLE
please do not rewrite tags

### ISSUE THREAD

**Issue by majewsky** [brianreumere/gandi-automatic-dns#40]
There were some shenanigans happening with the tags, and now the PKGBUILD for 2.2.0 does not build because checksums do not match. Please make a new release tag that was not used before, and please refrain from rewriting historical tags, to make downstream's job easier.

**Comment by brianreumere** [comment]
My bad, I should have checked if the package build had already happened for 2.2.0. I just pushed 2.3.0 to fix things.
